### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by Nightfallen** [Nightfallen/EquiLand#3]
### TODO List:

- [x] Fix #1 
- [x] Create application style
- [x] Add Alt menu bar
- [x] Add settings window
- [x] Disabled selectables background 
- [x] Make Selected selectables background brighter
- [x] Create Read-Only text input for range with 'Copy Range' possibility
- [x] Add RangedSlider to 'RangeSelect' widget
- [x] Implement displaying current range's combos and percentage (e.g. AA - 6 combos and 0.45%)
- [x] Make child windows splitters visible only when hovered
- [x] Create Frame instead of buttons with appropriate size for selected cards from 'BoardSelect' widget
- [x] Add new font with poker icons (or possibly create custom font with necessary icons including poker icons)
- [x] Add icons in Frames of 'BoardSelect' widget

**Comment by Nightfallen** [comment]
Style was introduced by bb459d56da06bf016de3e3b7c9e3baacfd9ea9d9

**Comment by Nightfallen** [comment]
Menu was introduced by e7f94874404dc9d54cf3f884848a2c18a8d94cad

**Comment by Nightfallen** [comment]
Disabled ```ImGui::Selectable``` background was introduced in e7f94874404dc9d54cf3f884848a2c18a8d94cad

**Comment by Nightfallen** [comment]
Added new tasks

**Comment by Nightfallen** [comment]
Frame instead of buttons with appropriate size for selected cards from 'BoardSelect' widget won't be implemented, it's simpler to leave button but set their active, hovered colors same as the button color itself and maybe in future there will be some more analysis tools so the buttons will come to play

**Comment by Nightfallen** [comment]
Due to complexity of some tasks, they were moved to separate issues, current issue is about small and simple ui enhancements.
- [ ] #11 
- [ ] #12
